define({
  "widgets": {
    "geoEnrichment": {
      "placeholder": {
        "enterValue": "Távolság megadása",
        "layerName": "Adja meg itt a réteg nevét"
      },
      "message": {
        "analysisFailed": "Nem sikerült az elemzés.",
        "errorOccurred": "Hiba történt.",
        "layerAdded": "A réteg hozzáadása megtörtént. ",
        "enrichLayerNameError": "Az eredményréteg neve nem tartalmazhat érvénytelen karaktereket\" + \"(<,>,#,%,:,\",?,&,+,/,\\).",
        "creatingService": "Szolgáltatás létrehozása... ",
        "starting": "Kezdés",
        "performingAnalysis": "Elemzés végrehajtása...",
        "checkLayerName": "Réteg nevének ellenőrzése... ",
        "addingLayer": "Réteg hozzáadása a webtérképhez ",
        "layerNameExist": "A rétegnév már létezik.",
        "clickOnSave": " Kattintson a Mentés gombra az alkalmazás újbóli betöltéséhez.",
        "clickOnOk": " Kattintson az OK gombra az újbóli próbálkozáshoz.",
        "enterNumbersOnly": "A megadott értékek nem érvényesek",
        "nofeatures": "Az aktuális kiterjedésben nincsenek vektoros elemek",
        "selectData": "Válasszon adatokat a réteg bővítéséhez.",
        "resetVariableMessage": "Biztos, hogy visszaállítja a változót?",
        "emptyTextFieldLayerName": "Eredményréteg nevének megadása",
        "createService": "A réteg nem lett létrehozva.",
        "sharingLayer": "Réteg megosztása...",
        "updateItemFailed": "Nem sikerült a frissítés. Próbálja meg újra.",
        "geoEnrichFailed": "Nem sikerült a réteg bővítése. Próbálja meg újra.",
        "shareFailed": "Nem sikerült a bővített réteg megosztása. Próbálja meg újra.",
        "refreshServiceFailed": "Nem sikerült a réteg frissítése. Próbálja meg újra.",
        "layerJsonFailed": "Nem sikerült JSON-t létrehozni a réteghez. Próbálja meg újra.",
        "addToWebmapFailed": "Nem sikerült hozzáadni a réteget a webtérképhez. Próbálja meg újra.",
        "bufferAreaHelpText": "Adjon meg olyan értéket, amely kisebb, mint ",
        "invalidBufferInput": "A megadott érték nem érvényes.",
        "emptyBufferInput": "Adjon meg érvényes értéket."
      },
      "populationText": "Népesség",
      "housingText": "Háztartás",
      "businessText": "Üzlet",
      "variableListText": " változói vannak felsorolva itt:",
      "countrySelectTitle": "1. Adatok helyének kiválasztása",
      "unitedStates": "Egyesült Államok",
      "global": "Globális",
      "geoenrichDialogText": "Téradat-bővítési változók",
      "viewVariablestext": "Változók megtekintése",
      "backButtonText": "Vissza",
      "customizeVariables": "Változók testreszabása",
      "resetVariables": "Visszaállítás",
      "defineAreaTitle": "3. Bővítendő terület meghatározása",
      "currentMapExtent": "Aktuális térképkiterjedés használata",
      "enrichLayerName": "4. Eredményréteg neve",
      "lineDistanceText": "Vonal távolsága",
      "drivingTime": "Utazási idő",
      "enrichButtonText": "Rétegbővítés",
      "selectDataText": "2. Adatok kiválasztása",
      "showCreditsText": "Kreditek megjelenítése",
      "variableCount": "Változók száma összesen ",
      "totalRecords": "Összes rekord:",
      "cost": "Költség:",
      "showCreditsDialogText": "Kreditek megjelenítése",
      "nextButtonText": "Következő",
      "prevButtonText": "Előző",
      "saveButtonText": "Mentés",
      "ok": "OK"
    }
  }
});