define({
  "widgets": {
    "TemplateBuilder": {
      "enterBuilderButtonText": "Belépés a szerkesztőbe",
      "exitBuilderButtonText": "Kilépés a szerkesztőből",
      "enterBuilderModeHelpText": "Belépés építő módba az alkalmazás konfigurálásához",
      "builderModeHelpText": "Sablonszerkesztő mód",
      "webmapCaption": "Térkép",
      "displaying": "megjelenítés",
      "selectMapMessage": "Jelenleg ${displaying}: <b>${webmapTitle}</b><br/>Másik webtérkép választásához kattintson a Térkép kiválasztása gombra",
      "loadMapMessage": "Jelenleg kiválasztva: <b>${webmapTitle}</b><br/>A webtérkép használatához kattintson a Mentés gombra",
      "changeWebmap": "Térkép kiválasztása",
      "saveButtonText": "Mentés",
      "webmapNextButtonText": "Következő ->",
      "previousButtonText": "Előző",
      "layerLabelText": "Réteg",
      "noLayerFoundText": "Nem található réteg",
      "selectLayer": "Réteg kiválasztása",
      "appProxiesText": "Előfizetői hozzáférés",
      "appProxiesDesc": "Ha engedélyezni szeretné az előfizetésén keresztüli nyilvános hozzáférést, jelölje be a megfelelő négyzeteket. A prémium tartalomként megjelölt tartalom krediteket használ fel az előfizetéséből.",
      "applicationSettingText": "Alkalmazás beállításai",
      "summaryAttrAscendingOrderTooltip": "Növekvő",
      "onStartLabel": "Kezdéskor",
      "selectVariableText": "Változó kiválasztása",
      "selectVariableDropdown": "Változó kiválasztása",
      "label": "Felirat",
      "sourceLinkText": "Forrás hivatkozása",
      "selectSubVariableText": "Alváltozók kiválasztása",
      "subVariablePanelButtonText": "KÉSZ",
      "onButtonLabel": "Be",
      "offButtonLabel": "Ki",
      "appSettingsSaveCloseButtonText": "MENTÉS ÉS BEZÁRÁS",
      "appSettingsTitleText": "Alkalmazás címe",
      "appSettingsDescriptionText": "Alkalmazás leírása",
      "appSetingsRendererAreaText": "Renderelt terület",
      "shareText": "Megosztás",
      "popupText": "Felugró ablak",
      "basemapText": "Alaptérkép",
      "cancel": "Mégse",
      "theme": "Téma",
      "zoomLevel": "Nagyítási szint",
      "existingValue": "Meglévő értékek használata",
      "enrichLayer": "Rétegbővítés",
      "imageLabel": "Hogyan működik?",
      "clearData": "Adatok törlése",
      "basemapSelectionText": "Alaptérkép kiválasztása",
      "secondaryBasemapText": "Másodlagos alaptérkép",
      "defaultBasemapText": "Alapértelmezett alaptérkép",
      "entireAreaButton": "Teljes terület",
      "entireAreaOnStartButton": "Teljes terület kezdéskor",
      "aboutPanel": "A panel névjegye",
      "legendPanel": "Jelmagyarázat panelje",
      "layersPanel": "Rétegek panelje",
      "dataConfigurationButtonText": "Adatkonfiguráció",
      "savingChangesMessage": "Módosítások mentése...",
      "nextButtonText": "Következő",
      "prevButtonText": "Előző",
      "enterLabelText": "Felirat megadása",
      "SelectedFeatureText": "Kijelölt vektoros elem",
      "layerHelpTextMessage": "Ez az alkalmazás numerikus mezőket tartalmazó réteget igényel",
      "alertMessage": {
        "resetVariableMessage": "Biztos, hogy visszaállítja a változót?",
        "emptyAppTitleMessage": "Az alkalmazás címe nem lehet üres",
        "emptyDescriptionMessage": "A leírás nem lehet üres",
        "maxVariableSelection": "25-nél több alváltozót nem választhat",
        "signInFail": "Nem sikerült a bejelentkezés",
        "itemUpdateMessage": "Elem frissítve",
        "unsavedChangesMessage": "Nem mentett módosítások",
        "failMessage": "Nem sikerült frissíteni az elemet",
        "saveChangesAlert": "Menti a módosításokat?",
        "variableLabelValidation": "A változó felirata nem lehet üres",
        "subVariableLabelValidation": "Az alváltozó felirata nem lehet üres"
      }
    }
  }
});