define({
  "widgets": {
    "geoEnrichment": {
      "placeholder": {
        "enterValue": "Introduïu la distància",
        "layerName": "Introduïu aquí el nom de la capa"
      },
      "message": {
        "analysisFailed": "Error en l'anàlisi.",
        "errorOccurred": "S'ha produït un error.",
        "layerAdded": "La capa s'ha afegit correctament. ",
        "enrichLayerNameError": "El valor de \"Nom de la capa de resultats\" no hauria de contenir els caràcters no vàlids \" + \" (<,>,#,%,:,\",?,&,+,/,\\).",
        "creatingService": "S'està creant el servei... ",
        "starting": "S'està iniciant",
        "performingAnalysis": "S'està fent l'anàlisi...",
        "checkLayerName": "S'està comprovant el nom de la capa... ",
        "addingLayer": "S'està afegint la capa al mapa web ",
        "layerNameExist": "El nom de la capa ja existeix.",
        "clickOnSave": " Feu clic al botó \"Desa\" per tornar a carregar l'aplicació.",
        "clickOnOk": " Feu clic al botó \"D'acord\" per tornar-ho a provar.",
        "enterNumbersOnly": "Els valors que s'han introduït no són vàlids",
        "nofeatures": "No hi ha cap entitat a l'extensió actual",
        "selectData": "Seleccioneu dades per enriquir la capa.",
        "resetVariableMessage": "Segur que voleu restablir la variable?",
        "emptyTextFieldLayerName": "Introduïu el nom de la capa de resultats",
        "createService": "La capa no s'ha creat.",
        "sharingLayer": "S'està compartint la capa...",
        "updateItemFailed": "No s'ha pogut fer l'actualització. Torneu-ho a provar.",
        "geoEnrichFailed": "No s'ha pogut enriquir la capa. Torneu-ho a provar.",
        "shareFailed": "No s'ha pogut compartir la capa enriquida. Torneu-ho a provar.",
        "refreshServiceFailed": "No s'ha pogut actualitzar la capa. Torneu-ho a provar.",
        "layerJsonFailed": "No s'ha pogut crear el codi JSON per a la capa. Torneu-ho a provar.",
        "addToWebmapFailed": "No s'ha pogut afegir la capa al mapa web. Torneu-ho a provar.",
        "bufferAreaHelpText": "Introduïu el valor menor que ",
        "invalidBufferInput": "El valor que s'ha introduït no és vàlid.",
        "emptyBufferInput": "Introduïu un valor vàlid."
      },
      "populationText": "Població",
      "housingText": "Llar",
      "businessText": "Empresa",
      "variableListText": " les variables s'enumeren aquí:",
      "countrySelectTitle": "1. Seleccioneu la ubicació de les dades",
      "unitedStates": "Estats Units",
      "global": "Global",
      "geoenrichDialogText": "Variables de geoenriquiment",
      "viewVariablestext": "Visualitza les variables",
      "backButtonText": "Enrere",
      "customizeVariables": "Personalitza les variables",
      "resetVariables": "Restableix",
      "defineAreaTitle": "3. Definiu l'àrea que s'enriquirà",
      "currentMapExtent": "Utilitza l'extensió del mapa actual",
      "enrichLayerName": "4. Nom de la capa de resultats",
      "lineDistanceText": "Distància de la línia",
      "drivingTime": "Temps de conducció",
      "enrichButtonText": "Enriqueix la capa",
      "selectDataText": "2. Seleccioneu les dades",
      "showCreditsText": "Mostra els crèdits",
      "variableCount": "Recompte total de variables ",
      "totalRecords": "Registres totals:",
      "cost": "Cost:",
      "showCreditsDialogText": "Mostra els crèdits",
      "nextButtonText": "Següent",
      "prevButtonText": "Anterior",
      "saveButtonText": "Desa",
      "ok": "D'acord"
    }
  }
});