define({
  "widgets": {
    "TemplateBuilder": {
      "enterBuilderButtonText": "Accedeix al Builder",
      "exitBuilderButtonText": "Surt del Builder",
      "enterBuilderModeHelpText": "Inicia el mode de Builder per configurar l'aplicació",
      "builderModeHelpText": "Plantilla del mode de Builder",
      "webmapCaption": "Mapa",
      "displaying": "s'està visualitzant",
      "selectMapMessage": "Actualment ${displaying} <b>${webmapTitle}</b><br/>Feu clic a Selecciona un mapa per triar un altre mapa web",
      "loadMapMessage": "Actualment està seleccionat <b>${webmapTitle}</b><br/>Feu clic a Desa per fer servir aquest mapa web",
      "changeWebmap": "Selecciona un mapa",
      "saveButtonText": "Desa",
      "webmapNextButtonText": "Següent ->",
      "previousButtonText": "Anterior",
      "layerLabelText": "Capa",
      "noLayerFoundText": "No s'ha trobat cap capa",
      "selectLayer": "Selecciona la capa",
      "appProxiesText": "Accés de subscriptor",
      "appProxiesDesc": "Per permetre l'accés públic a través de la vostra subscripció, activeu les caselles adequades. El contingut marcat com a Contingut Premium consumirà crèdits de la subscripció.",
      "applicationSettingText": "Configuració de l'aplicació",
      "summaryAttrAscendingOrderTooltip": "Ascendent",
      "onStartLabel": "A l'inici",
      "selectVariableText": "Seleccioneu una variable",
      "selectVariableDropdown": "Seleccioneu una variable",
      "label": "Etiqueta",
      "sourceLinkText": "Enllaç d'origen",
      "selectSubVariableText": "Seleccioneu subvariables",
      "subVariablePanelButtonText": "DONE",
      "onButtonLabel": "Activat",
      "offButtonLabel": "Desactivat",
      "appSettingsSaveCloseButtonText": "SAVE & CLOSE",
      "appSettingsTitleText": "Títol de l'aplicació",
      "appSettingsDescriptionText": "Descripció de l'aplicació",
      "appSetingsRendererAreaText": "Àrea renderitzada",
      "shareText": "Comparteix",
      "popupText": "Finestra emergent",
      "basemapText": "Mapa base",
      "cancel": "Cancel·la",
      "theme": "Tema",
      "zoomLevel": "Nivell de zoom",
      "existingValue": "Utilitza els valors existents",
      "enrichLayer": "Enriqueix la capa",
      "imageLabel": "Com funciona?",
      "clearData": "Esborra les dades",
      "basemapSelectionText": "Selecció del mapa base",
      "secondaryBasemapText": "Mapa base secundari",
      "defaultBasemapText": "Mapa base per defecte",
      "entireAreaButton": "Tota l'àrea",
      "entireAreaOnStartButton": "Tota l'àrea a l'inici",
      "aboutPanel": "Subfinestra Quant a",
      "legendPanel": "Subfinestra Llegenda",
      "layersPanel": "Subfinestra Capes",
      "dataConfigurationButtonText": "Configuració de dades",
      "savingChangesMessage": "S'estan desant els canvis...",
      "nextButtonText": "Següent",
      "prevButtonText": "Anterior",
      "enterLabelText": "Introduïu una etiqueta",
      "SelectedFeatureText": "Entitat seleccionada",
      "layerHelpTextMessage": "Aquesta aplicació necessita una capa amb camps numèrics",
      "alertMessage": {
        "resetVariableMessage": "Segur que voleu restablir la variable?",
        "emptyAppTitleMessage": "El títol de l'aplicació no pot estar buit",
        "emptyDescriptionMessage": "La descripció no pot estar buida",
        "maxVariableSelection": "No podeu seleccionar més de 25 subvariables",
        "signInFail": "Error d'inici de sessió",
        "itemUpdateMessage": "S'ha actualitzat l'element",
        "unsavedChangesMessage": "Canvis sense desar",
        "failMessage": "L'element no s'ha pogut actualitzar correctament",
        "saveChangesAlert": "Voleu desar els canvis?",
        "variableLabelValidation": "L'etiqueta de la variable no pot estar buida",
        "subVariableLabelValidation": "L'etiqueta de la subvariable no pot estar buida"
      }
    }
  }
});