define({
    "root": ({
        "widgets": {
            "TemplateBuilder": {
                "wemapCaption": "Webmap ID",
                "selectWebMap": "Step 1: Select a webmap id",
                "webmapTextBoxPlaceholder": "Enter webmap id",
                "webmapHelperText": "To get the webmap id, navigate to the details page for your webmap in ArcGIS.com. The webmap's ID is the value at the end of the url of the details page.",
                "saveButtonText": "Save",
                "nextButtonText":"Next ->",
                "selectImapctAreaLayerText": "Step 2: Select the layer to use as Impact Areas",
                "layerLabelText": "Layer",
                "noLayerFoundText": "No Layer Found",
                "labelLayerNameText": "Layer Name",
                "layerNamePlaceHolder": "Enter Layer Name",
                "applicationSettingText": "Application Setting",
                "next": "Next",
                "previous": "Previous",
                "source": "Data source",
                "showShareDialogText": "Show share dialog",
                "showAboutDialogText": "Show about dialog",
                "hideEntireAreaTootltip": "Hide Entire Area",
                "showEntireAreaTooltip": "Show Entire Area",
                "summaryAttrAscendingOrderTooltip": "Ascending",
                "summaryAttrDescendingOrderTooltip": "Descending",
                "selectVariableText":"Select A Variable",
                "label":"Label",
                "sourceLinkText":"Source Link",
                "selectSubVariableText":"Select Sub Variables",
                "subVariablePanelButtonText":"DONE",
                "resetVariableMessage":"Are You sure you want to reset variable ?"
            }
        }
    }),
    "ar": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sv": 1,
    "th": 1,
    "tr": 1,
    "zh-cn": 1
});