define({
  "widgets": {
    "geoEnrichment": {
      "placeholder": {
        "enterValue": "Masukkan jarak",
        "layerName": "Masukkan nama lapisan di sini"
      },
      "message": {
        "analysisFailed": "Analisis gagal.",
        "errorOccurred": "Terjadi beberapa kesalahan.",
        "layerAdded": "Lapisan berhasil ditambahkan. ",
        "enrichLayerNameError": "'Nama lapisan hasil' tidak boleh menggunakan karakter tidak valid \" + \"(<,>,#,%,:,\",?,&,+,/,\\).",
        "creatingService": "Membuat layanan... ",
        "starting": "Memulai",
        "performingAnalysis": "Melakukan analisis...",
        "checkLayerName": "Memeriksa nama lapisan... ",
        "addingLayer": "Menambahkan lapisan ke peta web... ",
        "layerNameExist": "Nama lapisan sudah ada.",
        "clickOnSave": " Klik tombol 'Simpan' untuk memuat ulang aplikasi.",
        "clickOnOk": " Klik tombol 'OKE' untuk mencoba lagi.",
        "enterNumbersOnly": "Nilai yang dimasukkan tidak valid",
        "nofeatures": "Tidak ada fitur yang ada di jangkauan saat ini",
        "selectData": "Silakan pilih data untuk memperkaya lapisan.",
        "resetVariableMessage": "Anda yakin ingin mengatur ulang variabel?",
        "emptyTextFieldLayerName": "Masukkan nama lapisan hasil",
        "createService": "Lapisan tidak dibuat.",
        "sharingLayer": "Berbagi lapisan...",
        "updateItemFailed": "Gagal memperbarui. Silakan coba lagi.",
        "geoEnrichFailed": "Gagal memperkaya lapisan. Silakan coba lagi.",
        "shareFailed": "Gagal membagikan lapisan yang diperkaya. Silakan coba lagi.",
        "refreshServiceFailed": "Gagal menyegarkan lapisan. Silakan coba lagi.",
        "layerJsonFailed": "Gagal membuat JSON untuk lapisan. Silakan coba lagi.",
        "addToWebmapFailed": "Gagal menambahkan lapisan ke peta web. Silakan coba lagi.",
        "bufferAreaHelpText": "Silakan masukkan nilai yang lebih kecil daripada ",
        "invalidBufferInput": "Nilai yang dimasukkan tidak valid.",
        "emptyBufferInput": "Masukkan nilai yang tepat."
      },
      "populationText": "Populasi",
      "housingText": "Rumah tangga",
      "businessText": "Bisnis",
      "variableListText": " variabel dicantumkan di sini:",
      "countrySelectTitle": "1. Pilih Lokasi Data",
      "unitedStates": "Amerika Serikat",
      "global": "Global",
      "geoenrichDialogText": "Variabel Geoenrichment",
      "viewVariablestext": "Tampilkan variabel",
      "backButtonText": "Kembali",
      "customizeVariables": "Sesuaikan variabel",
      "resetVariables": "Atur ulang",
      "defineAreaTitle": "3. Tentukan area yang akan diperkaya",
      "currentMapExtent": "Gunakan jangkauan peta saat ini",
      "enrichLayerName": "4. Nama lapisan hasil",
      "lineDistanceText": "Jarak Garis",
      "drivingTime": "Waktu Berkendara",
      "enrichButtonText": "Perkaya Lapisan",
      "selectDataText": "2. Pilih Data",
      "showCreditsText": "Tampilkan kredit",
      "variableCount": "Jumlah total variabel ",
      "totalRecords": "Total Rekaman:",
      "cost": "Biaya:",
      "showCreditsDialogText": "Tampilkan Kredit",
      "nextButtonText": "Berikutnya",
      "prevButtonText": "Sebelumnya",
      "saveButtonText": "Simpan",
      "ok": "OKE"
    }
  }
});