define({
  "widgets": {
    "TemplateBuilder": {
      "enterBuilderButtonText": "Masuk ke Penyusun",
      "exitBuilderButtonText": "Keluar dari Penyusun",
      "enterBuilderModeHelpText": "Masuk ke Mode Penyusun untuk mengonfigurasi aplikasi",
      "builderModeHelpText": "Mode Penyusun Pola Dasar",
      "webmapCaption": "Peta",
      "displaying": "menampilkan",
      "selectMapMessage": "Saat ini ${displaying} <b>${webmapTitle}</b><br/>Klik Pilih peta untuk memilih peta web yang berbeda",
      "loadMapMessage": "Saat ini dipilih <b>${webmapTitle}</b><br/>Klik Simpan untuk menggunakan peta web ini",
      "changeWebmap": "Pilih peta",
      "saveButtonText": "Simpan",
      "webmapNextButtonText": "Berikutnya ->",
      "previousButtonText": "Sebelumnya",
      "layerLabelText": "Lapisan",
      "noLayerFoundText": "Tidak Ditemukan Lapisan",
      "selectLayer": "Pilih Lapisan",
      "appProxiesText": "Akses Pelanggan",
      "appProxiesDesc": "Untuk mengizinkan akses publik melalui langganan Anda, centang kotak yang sesuai. Konten yang ditandai sebagai Konten Premium akan mengurangi kredit dari langganan Anda.",
      "applicationSettingText": "Pengaturan Aplikasi",
      "summaryAttrAscendingOrderTooltip": "Naik",
      "onStartLabel": "Saat Mulai",
      "selectVariableText": "Pilih Variabel",
      "selectVariableDropdown": "Pilih Variabel",
      "label": "Label",
      "sourceLinkText": "Tautan Sumber",
      "selectSubVariableText": "Pilih Sub-Variabel",
      "subVariablePanelButtonText": "SELESAI",
      "onButtonLabel": "Hidup",
      "offButtonLabel": "Mati",
      "appSettingsSaveCloseButtonText": "SIMPAN & TUTUP",
      "appSettingsTitleText": "Judul Aplikasi",
      "appSettingsDescriptionText": "Deskripsi Aplikasi",
      "appSetingsRendererAreaText": "Area yang Disajikan",
      "shareText": "Bagikan",
      "popupText": "Popup",
      "basemapText": "Peta Dasar",
      "cancel": "Batal",
      "theme": "Tema",
      "zoomLevel": "Tingkat Zoom",
      "existingValue": "Gunakan nilai yang ada",
      "enrichLayer": "Perkaya Lapisan",
      "imageLabel": "Bagaimana cara kerjanya?",
      "clearData": "Bersihkan Data",
      "basemapSelectionText": "Pilihan Peta Dasar",
      "secondaryBasemapText": "Peta Dasar Sekunder",
      "defaultBasemapText": "Peta Dasar Default",
      "entireAreaButton": "Seluruh Area",
      "entireAreaOnStartButton": "Keseluruhan Area saat mulai",
      "aboutPanel": "Tentang Panel",
      "legendPanel": "Panel Legenda",
      "layersPanel": "Panel Lapisan",
      "dataConfigurationButtonText": "Konfigurasi Data",
      "savingChangesMessage": "Menyimpan Perubahan...",
      "nextButtonText": "Berikutnya",
      "prevButtonText": "Sebelumnya",
      "enterLabelText": "Masukkan Label",
      "SelectedFeatureText": "Fitur yang Dipilih",
      "layerHelpTextMessage": "Aplikasi ini memerlukan lapisan dengan bidang numerik",
      "alertMessage": {
        "resetVariableMessage": "Anda yakin ingin mengatur ulang variabel?",
        "emptyAppTitleMessage": "Judul aplikasi tidak boleh kosong",
        "emptyDescriptionMessage": "Deskripsi tidak boleh kosong",
        "maxVariableSelection": "Anda tidak dapat memilih lebih dari 25 sub-variabel",
        "signInFail": "Gagal Masuk",
        "itemUpdateMessage": "Item Diperbarui",
        "unsavedChangesMessage": "Perubahan Belum Disimpan",
        "failMessage": "Tidak berhasil memperbarui item",
        "saveChangesAlert": "Apakah Anda ingin menyimpan perubahan?",
        "variableLabelValidation": "Label variabel tidak boleh kosong",
        "subVariableLabelValidation": "Label sub-variabel tidak boleh kosong"
      }
    }
  }
});