define({
  "widgets": {
    "TemplateBuilder": {
      "enterBuilderButtonText": "Přejít do nástroje pro tvorbu",
      "exitBuilderButtonText": "Opustit nástroj pro tvorbu",
      "enterBuilderModeHelpText": "Chcete-li nakonfigurovat aplikaci, přejděte do režimu tvorby.",
      "builderModeHelpText": "Režim tvorby šablon",
      "webmapCaption": "Mapa",
      "displaying": "probíhá zobrazení",
      "selectMapMessage": "Momentálně ${displaying} <b>${webmapTitle}</b><br/>Chcete-li zvolit jinou mapu, klikněte na tlačítko Vybrat mapu.",
      "loadMapMessage": "Momentálně vybráno <b>${webmapTitle}</b><br/>Chcete-li použít tuto webovou mapu, klikněte na tlačítko Uložit.",
      "changeWebmap": "Vybrat mapu",
      "saveButtonText": "Uložit",
      "webmapNextButtonText": "Další ->",
      "previousButtonText": "Předchozí",
      "layerLabelText": "Vrstva",
      "noLayerFoundText": "Nebyla nalezena žádná vrstva",
      "selectLayer": "Vybrat vrstvu",
      "appProxiesText": "Přístup pro předplatitele",
      "appProxiesDesc": "Chcete-li povolit veřejný přístup prostřednictvím předplatného, zaškrtněte příslušná políčka. Obsah označený jako Prémiový obsah bude z vašeho předplatného čerpat kredity.",
      "applicationSettingText": "Nastavení aplikace",
      "summaryAttrAscendingOrderTooltip": "Vzestupně",
      "onStartLabel": "Při spuštění",
      "selectVariableText": "Vyberte proměnnou",
      "selectVariableDropdown": "Vyberte proměnnou",
      "label": "Popisek",
      "sourceLinkText": "Zdrojový odkaz",
      "selectSubVariableText": "Vyberte podřízené proměnné",
      "subVariablePanelButtonText": "HOTOVO",
      "onButtonLabel": "Zapnuto",
      "offButtonLabel": "Vypnuto",
      "appSettingsSaveCloseButtonText": "ULOŽIT A ZAVŘÍT",
      "appSettingsTitleText": "Název aplikace",
      "appSettingsDescriptionText": "Popis aplikace",
      "appSetingsRendererAreaText": "Vykreslená oblast",
      "shareText": "Sdílet",
      "popupText": "Vyskakovací okno",
      "basemapText": "Podkladová mapa",
      "cancel": "Zrušit",
      "theme": "Motiv",
      "zoomLevel": "Úroveň přiblížení",
      "existingValue": "Použít existující hodnoty",
      "enrichLayer": "Obohatit vrstvu",
      "imageLabel": "Jak to funguje?",
      "clearData": "Vymazat data",
      "basemapSelectionText": "Výběr podkladové mapy",
      "secondaryBasemapText": "Sekundární podkladová mapa",
      "defaultBasemapText": "Výchozí podkladová mapa",
      "entireAreaButton": "Celá oblast",
      "entireAreaOnStartButton": "Celá oblast při spuštění",
      "aboutPanel": "Panel informací",
      "legendPanel": "Panel legendy",
      "layersPanel": "Panel vrstev",
      "dataConfigurationButtonText": "Datová konfigurace",
      "savingChangesMessage": "Ukládání změn...",
      "nextButtonText": "Další",
      "prevButtonText": "Předchozí",
      "enterLabelText": "Zadat popisek",
      "SelectedFeatureText": "Vybraný prvek",
      "layerHelpTextMessage": "Tato aplikace vyžaduje vrstvu s číselnými poli.",
      "alertMessage": {
        "resetVariableMessage": "Opravdu chcete obnovit proměnnou?",
        "emptyAppTitleMessage": "Název aplikace nesmí být prázdný",
        "emptyDescriptionMessage": "Popis nesmí být prázdný",
        "maxVariableSelection": "Nemůžete vybrat více než 25 podřízených proměnných",
        "signInFail": "Přihlášení se nezdařilo",
        "itemUpdateMessage": "Položka byla aktualizována",
        "unsavedChangesMessage": "Neuložené změny",
        "failMessage": "Položku se nepodařilo aktualizovat",
        "saveChangesAlert": "Chcete uložit změny?",
        "variableLabelValidation": "Popisek proměnné nesmí být prázdný.",
        "subVariableLabelValidation": "Popisek podřízené proměnné nesmí být prázdný."
      }
    }
  }
});