define({
  "widgets": {
    "geoEnrichment": {
      "placeholder": {
        "enterValue": "Vnesi razdaljo",
        "layerName": "Tukaj vnesite ime sloja"
      },
      "message": {
        "analysisFailed": "Analiza ni uspela.",
        "errorOccurred": "Prišlo je do napake.",
        "layerAdded": "Sloj je uspešno dodan. ",
        "enrichLayerNameError": "»Ime sloja z rezultati« ne sme vsebovati neveljavnih znakov\" + \"(<,>,#,%,:,\",?,&,+,/,\\).",
        "creatingService": "Ustvarjanje storitve.. ",
        "starting": "Začetek",
        "performingAnalysis": "Izvajanje analize…",
        "checkLayerName": "Preverjanje imena sloja.. ",
        "addingLayer": "Dodajanje sloja na spletno karto ",
        "layerNameExist": "Ime sloja že obstaja.",
        "clickOnSave": " Kliknite na gumb »Shrani«, da znova naložite aplikacijo.",
        "clickOnOk": " Kliknite na gumb »V redu« in poskusite znova.",
        "enterNumbersOnly": "Vnesene vrednosti niso veljavne",
        "nofeatures": "V trenutnem obsegu ni geoobjektov",
        "selectData": "Izberite podatke za geoobogatitev sloja.",
        "resetVariableMessage": "Ste prepričani, da želite ponastaviti spremenljivko?",
        "emptyTextFieldLayerName": "Vnesite ime sloja z rezultati",
        "createService": "Sloj ni bil ustvarjen.",
        "sharingLayer": "Deljenje sloja..",
        "updateItemFailed": "Posodobitev ni uspela. Poskusite znova.",
        "geoEnrichFailed": "Geoobogatitev sloja ni uspela. Poskusite znova.",
        "shareFailed": "Deljenje obogatenega sloja ni uspelo. Poskusite znova.",
        "refreshServiceFailed": "Osveževanje sloja ni uspelo. Poskusite znova.",
        "layerJsonFailed": "Ustvarjanje JSON za sloj ni uspelo. Poskusite znova.",
        "addToWebmapFailed": "Dodajanje sloja na spletno karto ni uspelo. Poskusite znova.",
        "bufferAreaHelpText": "Vnesite vrednost, manjšo kot ",
        "invalidBufferInput": "Vnesena vrednost ni veljavna.",
        "emptyBufferInput": "Vnesite veljavno vrednost."
      },
      "populationText": "Prebivalstvo",
      "housingText": "Gospodinjstvo",
      "businessText": "Poslovno",
      "variableListText": " spremenljivke so navedene tukaj:",
      "countrySelectTitle": "1. Izberi lokacijo podatkov",
      "unitedStates": "Združene države Amerike",
      "global": "Globalno",
      "geoenrichDialogText": "Spremenljivke geoobogatitve",
      "viewVariablestext": "Ogled spremenljivk",
      "backButtonText": "Nazaj",
      "customizeVariables": "Prilagodi spremenljivke",
      "resetVariables": "Ponastavite",
      "defineAreaTitle": "3. Določite območje za geoobogatitev",
      "currentMapExtent": "Uporabi trenutni obseg karte",
      "enrichLayerName": "4. Ime sloja z rezultati",
      "lineDistanceText": "Linijska razdalja",
      "drivingTime": "Trajanje vožnje",
      "enrichButtonText": "Geoobogati sloj",
      "selectDataText": "2. Izberite podatke",
      "showCreditsText": "Prikaži kredite",
      "variableCount": "Skupno število spremenljivk ",
      "totalRecords": "Skupaj zapisov:",
      "cost": "Stroški:",
      "showCreditsDialogText": "Prikaži kredite",
      "nextButtonText": "Naslednji",
      "prevButtonText": "Prejšnji",
      "saveButtonText": "Shrani",
      "ok": "V redu"
    }
  }
});