define({
  "widgets": {
    "TemplateBuilder": {
      "enterBuilderButtonText": "Vstop v graditelja",
      "exitBuilderButtonText": "Izhod iz graditelja",
      "enterBuilderModeHelpText": "Vstopite v graditeljski način, da konfigurirate aplikacijo",
      "builderModeHelpText": "Graditeljski način predlog",
      "webmapCaption": "Karta",
      "displaying": "prikazovanje",
      "selectMapMessage": "Trenutno ${displaying} <b>${webmapTitle}</b><br/>Kliknite Izberi karto, če želite izbrati drugo spletno karto",
      "loadMapMessage": "Trenutno je izbrana <b>${webmapTitle}</b><br/>Kliknite Shrani, če želite uporabiti to spletno karto",
      "changeWebmap": "Izberi karto",
      "saveButtonText": "Shrani",
      "webmapNextButtonText": "Naslednji ->",
      "previousButtonText": "Prejšnji",
      "layerLabelText": "Sloj",
      "noLayerFoundText": "Sloj ni najden",
      "selectLayer": "Izberi sloj",
      "appProxiesText": "Dostop za naročnike",
      "appProxiesDesc": "Če želite omogočiti javni dostop prek svoje naročnine, obkljukajte ustrezna polja. Vsebina, označena kot premium vsebina, bo porabljala kredite iz vaše naročnine.",
      "applicationSettingText": "Nastavitve aplikacije",
      "summaryAttrAscendingOrderTooltip": "Naraščajoče",
      "onStartLabel": "Na začetku",
      "selectVariableText": "Izberite spremenljivko",
      "selectVariableDropdown": "Izberite spremenljivko",
      "label": "Napis",
      "sourceLinkText": "Izvorna povezava",
      "selectSubVariableText": "Izberite podspremenljivke",
      "subVariablePanelButtonText": "KONČANO",
      "onButtonLabel": "Vklop",
      "offButtonLabel": "Izklop",
      "appSettingsSaveCloseButtonText": "SHRANI IN ZAPRI",
      "appSettingsTitleText": "Ime aplikacije",
      "appSettingsDescriptionText": "Opis aplikacije",
      "appSetingsRendererAreaText": "Upodobljeno območje",
      "shareText": "Deli",
      "popupText": "Pojavno okno",
      "basemapText": "Temeljna karta",
      "cancel": "Prekliči",
      "theme": "Tema",
      "zoomLevel": "Stopnja povečave",
      "existingValue": "Uporabi obstoječe vrednosti",
      "enrichLayer": "Geoobogati sloj",
      "imageLabel": "Kako to deluje?",
      "clearData": "Počisti podatke",
      "basemapSelectionText": "Izbira temeljne karte",
      "secondaryBasemapText": "Sekundarna temeljna karta",
      "defaultBasemapText": "Privzeta temeljna karta",
      "entireAreaButton": "Celotno območje",
      "entireAreaOnStartButton": "Celotno območje na začetku",
      "aboutPanel": "Plošča za več informacij",
      "legendPanel": "Plošča za legendo",
      "layersPanel": "Plošča slojev",
      "dataConfigurationButtonText": "Konfiguracija podatkov",
      "savingChangesMessage": "Shranjevanje sprememb...",
      "nextButtonText": "Naslednji",
      "prevButtonText": "Prejšnji",
      "enterLabelText": "Vnesi napis",
      "SelectedFeatureText": "Izbrani geoobjekt",
      "layerHelpTextMessage": "Ta aplikacija zahteva sloj s številskimi polji",
      "alertMessage": {
        "resetVariableMessage": "Ste prepričani, da želite ponastaviti spremenljivko?",
        "emptyAppTitleMessage": "Ime aplikacije ne sme biti prazno",
        "emptyDescriptionMessage": "Opis ne sme biti prazen",
        "maxVariableSelection": "Več kot 25 podspremenljivk ne morete izbrati",
        "signInFail": "Prijava ni uspela",
        "itemUpdateMessage": "Element je posodobljen",
        "unsavedChangesMessage": "Neshranjene spremembe",
        "failMessage": "Posodabljanje elementa ni bilo uspešno",
        "saveChangesAlert": "Ali želite shraniti spremembe?",
        "variableLabelValidation": "Napis spremenljivke ne sme biti prazen",
        "subVariableLabelValidation": "Napis podspremenljivke ne sme biti prazen"
      }
    }
  }
});