define({
  "widgets": {
    "geoEnrichment": {
      "placeholder": {
        "enterValue": "दूरी दर्ज करें",
        "layerName": "यहाँ लेयर का नाम दर्ज करें"
      },
      "message": {
        "analysisFailed": "विश्लेषण विफल रहा।",
        "errorOccurred": "कुछ त्रुटि उत्पन्न हुई।",
        "layerAdded": "लेयर को सफलतापूर्वक सम्मिलित कर लिया गया। ",
        "enrichLayerNameError": "'परिणामित लेयर का नाम' में अमान्य अक्षर नहीं होने चाहिए\" \"+\" (<,>, #,%,:? \", &, +, /, \\)।",
        "creatingService": "सेवा बनाई जा रही है.. ",
        "starting": "प्रारंभ हो रहा है",
        "performingAnalysis": "विश्लेषण किया जा रहा है..",
        "checkLayerName": "लेयर के नाम के लिए जाँच हो रही है.. ",
        "addingLayer": "वेब मैप में लेयर सम्मिलित की जा रही है ",
        "layerNameExist": "लेयर का नाम पहले से ही मौजूद है।",
        "clickOnSave": " ऐप्लिकेशन को फिर से लोड करने के लिए 'सहेजें' बटन पर क्लिक करें।",
        "clickOnOk": " फिर से कोशिश करने के लिए कृपया 'ठीक है' बटन पर क्लिक करें।",
        "enterNumbersOnly": "दर्ज की गई संख्याएँ मान्य नहीं है",
        "nofeatures": "वर्तमान सीमा में कोई सुविधाएं मौजूद नहीं हैं",
        "selectData": "लेयर को समृद्ध करने के लिए कृपया डेटा का चयन करें।",
        "resetVariableMessage": "क्या आप वाकई चर रिसेट करना चाहते हैं?",
        "emptyTextFieldLayerName": "परिणामित लेयर का नाम दर्ज करें",
        "createService": "लेयर नहीं बनाई गई।",
        "sharingLayer": "लेयर साझा की जा रही है..",
        "updateItemFailed": "अपडेट करने में विफल। कृपया पुनः प्रयास करें।",
        "geoEnrichFailed": "लेयर समृद्ध करने में विफल। कृपया पुनः प्रयास करें।",
        "shareFailed": "समृद्ध लेयर साझा करने में विफल। कृपया पुनः प्रयास करें।",
        "refreshServiceFailed": "लेयर ताज़ा करने में विफल। कृपया पुनः प्रयास करें।",
        "layerJsonFailed": "लेयर के लिए JSON बनाने में विफल। कृपया पुनः प्रयास करें।",
        "addToWebmapFailed": "वेब मानचित्र में लेयर सम्मिलित करने में विफल। कृपया पुनः प्रयास करें।",
        "bufferAreaHelpText": "कृपया इससे कम संख्या दर्ज करें ",
        "invalidBufferInput": "दर्ज की गई संख्या मान्य नहीं है।",
        "emptyBufferInput": "कृपया मान्य मान दर्ज करें।"
      },
      "populationText": "जनसँख्या",
      "housingText": "गृहस्थी",
      "businessText": "व्यापार",
      "variableListText": " चर यहाँ सूचीबद्ध हैं:",
      "countrySelectTitle": "1. डेटा स्थान चुनें",
      "unitedStates": "संयुक्त राज्य",
      "global": "ग्लोबल",
      "geoenrichDialogText": "Geoenrichment चर",
      "viewVariablestext": "चर देखें",
      "backButtonText": "पीछे जाएँ",
      "customizeVariables": "चर अनुकूलित करें",
      "resetVariables": "रीसेट करें",
      "defineAreaTitle": "3. समृद्ध किए जाने वाला क्षेत्र परिभाषित करें",
      "currentMapExtent": "वर्तमान मानचित्र सीमा का प्रयोग करें",
      "enrichLayerName": "4. परिणामित लेयर का नाम",
      "lineDistanceText": "रेखा की दूरी",
      "drivingTime": "ड्राइविंग का समय",
      "enrichButtonText": "लेयर का मूल्य वर्द्धन करें",
      "selectDataText": "2. डेटा चुनें",
      "showCreditsText": "क्रेडिट दिखाएँ",
      "variableCount": "कुल परिवर्ती गिनती ",
      "totalRecords": "कुल अभिलेख:",
      "cost": "लागत:",
      "showCreditsDialogText": "क्रेडिट दिखाएँ",
      "nextButtonText": "अगला",
      "prevButtonText": "पिछला",
      "saveButtonText": "सहेजें",
      "ok": "ठीक है"
    }
  }
});