define({
  "widgets": {
    "TemplateBuilder": {
      "enterBuilderButtonText": "बिल्डर दर्ज करें",
      "exitBuilderButtonText": "बिल्डर से बाहर निकलें",
      "enterBuilderModeHelpText": "ऐप्लिकेशन को कॉन्फ़िगर करने के लिए बिल्डर मोड में प्रवेश करें",
      "builderModeHelpText": "टेम्पलेट बिल्डर मोड",
      "webmapCaption": "मानचित्र",
      "displaying": "प्रदर्शित करना",
      "selectMapMessage": "वर्तमान में ${displaying} <b>${webmapTitle}</b><br/>एक अलग वेब मैप का चयन करने के लिए मानचित्र चुनें पर क्लिक करें",
      "loadMapMessage": "वर्तमान में चयनित <b>${webmapTitle}</b><br/>इस वेब मैप का उपयोग करने हेतु सहेजें पर क्लिक करें",
      "changeWebmap": "मानचित्र चुनें",
      "saveButtonText": "सहेजें",
      "webmapNextButtonText": "अगला ->",
      "previousButtonText": "पिछला",
      "layerLabelText": "लेयर",
      "noLayerFoundText": "कोई लेयर नहीं मिली",
      "selectLayer": "लेयर चुनें",
      "appProxiesText": "सदस्य एक्सेस",
      "appProxiesDesc": "अपनी सदस्यता के ज़रिए सार्वजनिक एक्सेस की अनुमति देने के लिए उचित बॉक्स चुनें। ऐसी सामग्री जो प्रीमियम सामग्री के रूप में चिन्हित है वह आपकी सदस्यता से ज़्यादा क्रेडिट खर्च करेगी।",
      "applicationSettingText": "ऐप्लीकेशन सेटिंग",
      "summaryAttrAscendingOrderTooltip": "आरोही",
      "onStartLabel": "प्रारंभ पर",
      "selectVariableText": "कोई चर चुनें",
      "selectVariableDropdown": "कोई चर चुनें",
      "label": "लेबल",
      "sourceLinkText": "स्रोत लिंक",
      "selectSubVariableText": "कोई चर चुनें",
      "subVariablePanelButtonText": "हो गया",
      "onButtonLabel": "चालू",
      "offButtonLabel": "बंद",
      "appSettingsSaveCloseButtonText": "सहेजे और बंद करें",
      "appSettingsTitleText": "ऐप्लिकेशन का शीर्षक",
      "appSettingsDescriptionText": "ऐप्लिकेशन का विवरण",
      "appSetingsRendererAreaText": "प्रतिपादन किया गया क्षेत्र",
      "shareText": "साझा करें",
      "popupText": "पॉप-अप",
      "basemapText": "बेसमैप",
      "cancel": "रद्द करें",
      "theme": "थीम",
      "zoomLevel": "ज़ूम स्तर",
      "existingValue": "मौजूदा संख्याओं का प्रयोग करें",
      "enrichLayer": "लेयर का मूल्य वर्द्धन करें",
      "imageLabel": "यह कैसे काम करता है ?",
      "clearData": "स्पष्ट डेटा",
      "basemapSelectionText": "बेसमैप चुनें",
      "secondaryBasemapText": "माध्यमिक बेसमैप",
      "defaultBasemapText": "डिफ़ॉल्ट बेसमैप",
      "entireAreaButton": "संपूर्ण क्षेत्र",
      "entireAreaOnStartButton": "प्रारंभ पर पूर्ण क्षेत्र",
      "aboutPanel": "पैनल के बारे में",
      "legendPanel": "लीजेंड पैनल",
      "layersPanel": "लेयर्स पैनल",
      "dataConfigurationButtonText": "डेटा कॉन्फ़िगरेशन",
      "savingChangesMessage": "परिवर्तनों को सहेजा जा रहा है...",
      "nextButtonText": "अगला",
      "prevButtonText": "पिछला",
      "enterLabelText": "लेबल दर्ज करें",
      "SelectedFeatureText": "चयनित सुविधा",
      "layerHelpTextMessage": "इस ऐप्लिकेशन को संख्यात्मक फील्ड वाली लेयर की आवश्यकता है",
      "alertMessage": {
        "resetVariableMessage": "क्या आप वाकई चर रिसेट करना चाहते हैं?",
        "emptyAppTitleMessage": "ऐप्लिकेशन का शीर्षक रिक्त नहीं हो सकता है",
        "emptyDescriptionMessage": "विवरण खाली नहीं हो सकता है",
        "maxVariableSelection": "आप 25 से अधिक उप परिवर्ती चुन सकते हैं",
        "signInFail": "साइन इन विफल हुआ",
        "itemUpdateMessage": "आइटम अपडेट हो गया",
        "unsavedChangesMessage": "बिना सहेजे गए परिवर्तन",
        "failMessage": "सफलतापूर्वक आइटम में अपडेट नहीं कर सके",
        "saveChangesAlert": "क्या आप परिवर्तन सहेजना चाहते हैं?",
        "variableLabelValidation": "चर लेबल खाली नहीं हो सकता है",
        "subVariableLabelValidation": "उप चर लेबल खाली"
      }
    }
  }
});