define({
  "widgets": {
    "geoEnrichment": {
      "placeholder": {
        "enterValue": "Ввести відстань",
        "layerName": "Введіть назву шару тут"
      },
      "message": {
        "analysisFailed": "Аналіз не вдалося виконати.",
        "errorOccurred": "Виникла помилка.",
        "layerAdded": "Шар успішно додано. ",
        "enrichLayerNameError": "Назва шару результатів не повинна містити недійсних символів \" + \"(<,>,#,%,:,\",?,&,+,/,\\).",
        "creatingService": "Виконується створення сервісу... ",
        "starting": "Починається",
        "performingAnalysis": "Виконується аналіз...",
        "checkLayerName": "Виконується перевірка назви шару... ",
        "addingLayer": "Виконується додавання шару до веб-карти ",
        "layerNameExist": "Назва шару вже існує.",
        "clickOnSave": " Натисніть кнопку «Зберегти» для перезавантаження додатку.",
        "clickOnOk": " Натисніть кнопку «OK», щоб спробувати знову.",
        "enterNumbersOnly": "Введені значення недійсні",
        "nofeatures": "Об'єкти відсутні у поточному екстенті",
        "selectData": "Виберіть дату для збагачення шару.",
        "resetVariableMessage": "Бажаєте скинути змінну?",
        "emptyTextFieldLayerName": "Введіть назву шару результатів",
        "createService": "Шар не створено.",
        "sharingLayer": "Виконується надання спільного доступу до шару...",
        "updateItemFailed": "Не вдалося оновити. Спробуйте знову.",
        "geoEnrichFailed": "Не вдалося збагатити шар. Спробуйте знову.",
        "shareFailed": "Не вдалося поділитися збагаченим шаром. Спробуйте знову.",
        "refreshServiceFailed": "Не вдалося оновити шар. Спробуйте знову.",
        "layerJsonFailed": "Не вдалося створити JSON для шару. Спробуйте знову.",
        "addToWebmapFailed": "Не вдалося додати шар до веб-карти. Спробуйте знову.",
        "bufferAreaHelpText": "Введіть значення менше, ніж ",
        "invalidBufferInput": "Введене значення недійсне.",
        "emptyBufferInput": "Введіть дійсне значення."
      },
      "populationText": "Населення",
      "housingText": "Домогосподарство",
      "businessText": "Бізнес",
      "variableListText": " змінні наведено тут:",
      "countrySelectTitle": "1. Вибрати місце розташування даних",
      "unitedStates": "Сполучені Штати Америки",
      "global": "Весь світ",
      "geoenrichDialogText": "Змінні геозбагачення",
      "viewVariablestext": "Переглянути змінні",
      "backButtonText": "Назад",
      "customizeVariables": "Налаштувати змінні",
      "resetVariables": "Скинути",
      "defineAreaTitle": "3. Визначити область для збагачення",
      "currentMapExtent": "Використовувати поточний екстент карти",
      "enrichLayerName": "4. Ім'я шару результатів",
      "lineDistanceText": "Лінійна відстань",
      "drivingTime": "Час подорожі автомобілем",
      "enrichButtonText": "Збагатити шар",
      "selectDataText": "2. Виберіть дані",
      "showCreditsText": "Показати кредити",
      "variableCount": "Загальна кількість змінних ",
      "totalRecords": "Всього записів:",
      "cost": "Вартість:",
      "showCreditsDialogText": "Показати кредити",
      "nextButtonText": "Далі",
      "prevButtonText": "Назад",
      "saveButtonText": "Зберегти",
      "ok": "OK"
    }
  }
});