define({
  "widgets": {
    "TemplateBuilder": {
      "enterBuilderButtonText": "Увійти в конструктор",
      "exitBuilderButtonText": "Вийти з конструктора",
      "enterBuilderModeHelpText": "Увійти в режим конструктора для налаштування додатку",
      "builderModeHelpText": "Режим конструктора шаблону",
      "webmapCaption": "Карта",
      "displaying": "відображається",
      "selectMapMessage": "Зараз ${displaying} <b>${webmapTitle}</b><br/>Клацніть «Вибрати карту», щоб вибрати іншу веб-карту",
      "loadMapMessage": "Зараз вибрано <b>${webmapTitle}</b><br/>Клацніть «Зберегти»,щоб використовувати цю веб-карту",
      "changeWebmap": "Вибрати карту",
      "saveButtonText": "Зберегти",
      "webmapNextButtonText": "Далі ->",
      "previousButtonText": "Назад",
      "layerLabelText": "Шар",
      "noLayerFoundText": "Шар не знайдено",
      "selectLayer": "Вибрати шар",
      "appProxiesText": "Доступ передплатника",
      "appProxiesDesc": "Щоб дозволити публічний доступ через вашу підписку, відмітьте відповідні поля. Зміст, позначений як «Преміальний зміст» вимагає оплату кредитами з вашої підписки.",
      "applicationSettingText": "Налаштування додатку",
      "summaryAttrAscendingOrderTooltip": "У висхідному порядку",
      "onStartLabel": "На початку",
      "selectVariableText": "Вибрати змінну",
      "selectVariableDropdown": "Вибрати змінну",
      "label": "Напис",
      "sourceLinkText": "Посилання на джерело",
      "selectSubVariableText": "Вибрати компонент змінної",
      "subVariablePanelButtonText": "ГОТОВО",
      "onButtonLabel": "Увімкн.",
      "offButtonLabel": "Вимкн.",
      "appSettingsSaveCloseButtonText": "ЗБЕРЕГТИ ТА ЗАКРИТИ",
      "appSettingsTitleText": "Заголовок додатка",
      "appSettingsDescriptionText": "Опис додатка",
      "appSetingsRendererAreaText": "Відображена область",
      "shareText": "Поділитися",
      "popupText": "Спливаюче вікно",
      "basemapText": "Базова карта",
      "cancel": "Скасувати",
      "theme": "Тема",
      "zoomLevel": "Рівень масштабування",
      "existingValue": "Використовувати існуючі значення",
      "enrichLayer": "Збагатити шар",
      "imageLabel": "Як це працює?",
      "clearData": "Очистити дані",
      "basemapSelectionText": "Вибір базової карти",
      "secondaryBasemapText": "Допоміжна базова карта",
      "defaultBasemapText": "Базова карта за замовчуванням",
      "entireAreaButton": "Вся область",
      "entireAreaOnStartButton": "Вся область на початку",
      "aboutPanel": "Про панель",
      "legendPanel": "Панель легенди",
      "layersPanel": "Панель шарів",
      "dataConfigurationButtonText": "Конфігурація даних",
      "savingChangesMessage": "Виконується збереження змін...",
      "nextButtonText": "Далі",
      "prevButtonText": "Назад",
      "enterLabelText": "Ввести напис",
      "SelectedFeatureText": "Вибраний об'єкт",
      "layerHelpTextMessage": "Для цього додатку потрібен шар з числовими полями",
      "alertMessage": {
        "resetVariableMessage": "Бажаєте скинути змінну?",
        "emptyAppTitleMessage": "Заголовок додатку не може бути порожнім",
        "emptyDescriptionMessage": "Опис не може бути порожнім",
        "maxVariableSelection": "Ви не можете вибрати більше 25 компонентів змінної",
        "signInFail": "Не вдалося увійти в систему",
        "itemUpdateMessage": "Елемент оновлено",
        "unsavedChangesMessage": "Незбережені зміни",
        "failMessage": "Не вдалося успішно оновити елемент",
        "saveChangesAlert": "Бажаєте зберегти зміни?",
        "variableLabelValidation": "Напис змінної не може бути порожнім",
        "subVariableLabelValidation": "Напис компоненту змінної не може бути порожнім"
      }
    }
  }
});