define({
  "widgets": {
    "TemplateBuilder": {
      "enterBuilderButtonText": "Atvērt veidotāju",
      "exitBuilderButtonText": "Aizvērt veidotāju",
      "enterBuilderModeHelpText": "Atvērt veidotāja režīmu, lai konfigurētu lietotni",
      "builderModeHelpText": "Veidņu veidotāja režīms",
      "webmapCaption": "Karte",
      "displaying": "rāda",
      "selectMapMessage": "Pašreiz ${displaying} <b>${webmapTitle}</b><br/>Noklikšķiniet uz Atlasīt karti, lai izvēlētos citu tīmekļa karti.",
      "loadMapMessage": "Pašreiz atlasīts <b>${webmapTitle}</b><br/>Noklikšķiniet uz Saglabāt, lai izmantotu šo tīmekļa karti.",
      "changeWebmap": "Atlasīt karti",
      "saveButtonText": "Saglabāt",
      "webmapNextButtonText": "Tālāk ->",
      "previousButtonText": "Iepriekšējais",
      "layerLabelText": "Slānis",
      "noLayerFoundText": "Nav atrasts neviens slānis",
      "selectLayer": "Atlasīt slāni",
      "appProxiesText": "Abonenta piekļuve",
      "appProxiesDesc": "Lai atļautu publisku piekļuvi, izmantojot jūsu abonementu, atzīmējiet atbilstošās izvēles rūtiņas. Saturs, kas atzīmēts kā augstākās klases saturs, tērēs jūsu abonementa servisa kredītus.",
      "applicationSettingText": "Lietotnes iestatījumi",
      "summaryAttrAscendingOrderTooltip": "Pieaugošs",
      "onStartLabel": "Sākot",
      "selectVariableText": "Atlasīt mainīgo",
      "selectVariableDropdown": "Atlasīt mainīgo",
      "label": "Kartes teksts",
      "sourceLinkText": "Avota saite",
      "selectSubVariableText": "Atlasīt papildu mainīgos",
      "subVariablePanelButtonText": "Pabeigts",
      "onButtonLabel": "Ieslēgt",
      "offButtonLabel": "Izslēgt",
      "appSettingsSaveCloseButtonText": "Saglabāt un aizvērt",
      "appSettingsTitleText": "Lietotnes nosaukums",
      "appSettingsDescriptionText": "Lietotnes apraksts",
      "appSetingsRendererAreaText": "Renderēta teritorija",
      "shareText": "Koplietot",
      "popupText": "Uznirstošais logs",
      "basemapText": "Pamatkarte",
      "cancel": "Atcelt",
      "theme": "Tēma",
      "zoomLevel": "Mērogmaiņas līmenis",
      "existingValue": "Lietot esošās vērtības",
      "enrichLayer": "Bagātināt slāni",
      "imageLabel": "Kā tas darbojas?",
      "clearData": "Notīrīt datus",
      "basemapSelectionText": "Pamatkartes atlasīšana",
      "secondaryBasemapText": "Sekundārā pamatkarte",
      "defaultBasemapText": "Noklusējuma pamatkarte",
      "entireAreaButton": "Viss laukums",
      "entireAreaOnStartButton": "Viss laukums sākot",
      "aboutPanel": "Par paneli",
      "legendPanel": "Apzīmējumu panelis",
      "layersPanel": "Slāņu panelis",
      "dataConfigurationButtonText": "Datu konfigurācija",
      "savingChangesMessage": "Izmaiņu saglabāšana...",
      "nextButtonText": "Tālāk",
      "prevButtonText": "Iepriekšējais",
      "enterLabelText": "Ievadīt kartes tekstu",
      "SelectedFeatureText": "Atlasītais elements",
      "layerHelpTextMessage": "Šai lietotnei nepieciešams slānis ar skaitliskiem laukiem",
      "alertMessage": {
        "resetVariableMessage": "Vai tiešām vēlaties atiestatīt mainīgo?",
        "emptyAppTitleMessage": "Obligāti jānorāda lietotnes nosaukums",
        "emptyDescriptionMessage": "Onligāti jānorāda lietotnes apraksts",
        "maxVariableSelection": "Nevarat atlasīt vairāk par 25 papildu mainīgajiem",
        "signInFail": "Pierakstīšanās neizdevās",
        "itemUpdateMessage": "Vienība atjaunināta",
        "unsavedChangesMessage": "Nesaglabātās izmaiņas",
        "failMessage": "Nevarēja veiksmīgi atjaunināt vienību",
        "saveChangesAlert": "Vai vēlaties saglabāt izmaiņas?",
        "variableLabelValidation": "Mainīgais kartes apraksts nevar būt tukšs",
        "subVariableLabelValidation": "Papildu mainīgais kartes apraksts nevar būt tukšs"
      }
    }
  }
});